export const regions = ["DE", "EN", "ES", "FR", "IT", "BD"];
export const names = {
  DE: [
    "michael",
    "felix",
    "caroline",
    "evelyn",
    "fred",
    "george",
    "Ana",
    "Andreas",
    "Anja",
    "Anna",
    "Friedrich",
    "Goethe",
    "Hans",
    "Helmut",
    "Jasmina",
    "Jonas",
    "Kathrin",
    "Klaus",
    "Laura",
    "Lea",
    "Wolf",
    "Matias",
    "Moritz",
    "Otto",
    "Paul",
    "Walter",
    "Wilhelm"
  ],
  ES: [
    "angelo",
    "danilo",
    "ronaldo",
    "emmanuel",
    "angela",
    "amigo",
    "gustavo",
    "Santiago",
    "Matias",
    "Diego",
    "Samuel",
    "Sebastian"
  ],
  IT: ["rachele", "ekkia", "lorenzo", "mamamia"],
  FR: ["thomas", "marc", "paris", "luis"],
  EN: ["jonathan", "marry", "jones", "jacky", "Dave"],
  RU: [
    "Vladimir",
    "Sergey",
    "Mikhail",
    "Mike",
    "Andrey",
    "Anton",
    "Yaroslav",
    "Olexi",
    "Alexi",
    "Ilya",
    "Roman",
    "Sophia",
    "Marina"
  ],
  BD: [
    "Mehedi",
    "Shourav",
    "Kaysar",
    "Abdul",
    "Sadia",
    "Hridi",
    "Fariha",
    "Anik",
    "Shammo",
    "Bijoy",
    "Sabbir",
    "Ashik",
    "Koushik",
    "Labib",
    "habib",
    "Babu",
    "Choton",
    "Riad",
    "Upol"
  ]
};
