language: node_js
node_js:
  - stable
  - '--lts'
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  yarn: true
  directories:
    - '~/.npm'
    - '~/.cache'
    - node_modules
script:
  - yarn build
  - yarn unit-test
# Percy is expensive run it only as PR checker
  - if [[ $TRAVIS_PULL_REQUEST == "true" ]]; then yarn test-integration-and-visual; fi
after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
env:
  global:
    secure: CDucdhHDvpf3vMBbaT7bdciPmWFHvzo45HVg0ydE4YGxjENwEG1MySteZxJNq6610ts9cLSqHIbYq+axtOaQofYOqhrllgDXiOUPBO0VXrOmteAT0r2N8zl9ZPQds3zdX2GkFFldq0YPbUGMQhA3V8WqNxUXWuMook8BSvnxPKwJy+QQoHFxGn7eG539gbI2wGMQ3XfwLv+Pop9LQMyI41I1TmMQTtVkbmS/QhvNvUy8S4HVr1abn1OssJlRMskycB4TWQIeTgg8hWlc1l+nFPo+aB0gQgSs7MvydKSrmETcL5ircTpFNdWh4erE2ua9E5ANN0HG6wPBa2a9aUdMu2HVbuO+LFY1vvxxuhULfh+M0RlOPgDiWCTGRR+FdjwrdNdfLd8zcIWHqddWlp1elOHdaCbcaERE5S9sFlwF2geKwBbWZYS5uEUS+R3NxZG5lUtKL2gUAHZQDMz3NfckUVa3E+thdnyuYCguo6+XCCAdUE7qPB24PAnjQlUHAltjXbxQSidYcFkb/XWmfmLWwsWRrssAlKpg7CMNXS5ZYmL4pQ6SZ7x46nlf6oBGxo6D6Hh+rmvePNYeHfZGlCJrmBmJyBTNmIUlIxBwKCHJ0+W95Z37RkNJsxQSbfmkBxZt7yeG7IcHoMw6A3DyDzElOikKhTlfhi9rswXDuSixBhE=
